text=input().lower()
a=text.count(" ")
text1=text.replace('@', " ")
text2=text1.replace('!', " ")
text3=text2.replace('#', " ")
text4=text3.replace('%', " ")
b=text4.count(" ")
print(b-a)
print(text4)
